services:
  db:
    image: postgres:16
    container_name: items-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: itemsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d itemsdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: items-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: itemsdb
      DB_USER: admin
      DB_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  db_data:
